// Regenerates frontend/src/data/georgiaResources.ts from backend/data/georgia_resources.json.
// Run manually: npm run sync-corpus. Not wired into prebuild (backend path may be missing on CI).

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(__dirname, "../../backend/data/georgia_resources.json");
const DEST = resolve(__dirname, "../src/data/georgiaResources.ts");

const ALLOWED_CATEGORIES = new Set([
  "education",
  "housing",
  "employment",
  "crisis",
  "healthcare",
  "legal",
  "benefits",
  "financial",
  "documents",
]);

const TYPE_CATEGORIES = [
  "education",
  "housing",
  "employment",
  "crisis",
  "healthcare",
  "legal",
  "benefits",
  "financial",
  "documents",
];

const CATEGORY_LABEL = {
  education: "Education",
  housing: "Housing",
  employment: "Work & training",
  crisis: "Crisis",
  healthcare: "Healthcare",
  legal: "Legal",
  benefits: "Benefits portal",
  financial: "Financial",
  documents: "Documents & ID",
};

const CATEGORY_ORDER = [
  "crisis",
  "housing",
  "healthcare",
  "education",
  "employment",
  "financial",
  "documents",
  "legal",
  "benefits",
];

const raw = JSON.parse(readFileSync(SRC, "utf8"));
if (!Array.isArray(raw)) throw new Error("Expected JSON array");

const unknown = raw.filter((r) => !ALLOWED_CATEGORIES.has(r.category));
if (unknown.length) {
  throw new Error(
    `Unknown categories — update ALLOWED_CATEGORIES + ResourceCategory type: ${
      [...new Set(unknown.map((r) => r.category))].join(", ")
    }`,
  );
}

const pick = (r) => ({
  id: r.id,
  name: r.name,
  category: r.category,
  county: r.county ?? "statewide",
  summary: r.summary ?? "",
  eligibility: r.eligibility ?? "",
  services: r.services ?? [],
  contact_phone: r.contact_phone ?? "",
  contact_url: r.contact_url ?? "",
  address: r.address ?? "",
  source_name: r.source_name ?? r.name,
  last_verified: r.last_verified ?? "",
});

const cleaned = raw.map(pick);

const typeUnion = TYPE_CATEGORIES.map((c) => `  | "${c}"`).join("\n");
const labelLines = TYPE_CATEGORIES.map(
  (c) => `  ${c}: "${CATEGORY_LABEL[c]}",`,
).join("\n");
const orderLines = CATEGORY_ORDER.map((c) => `  "${c}",`).join("\n");

const banner = `// AUTO-GENERATED by frontend/scripts/sync-corpus.mjs. Do not edit by hand.
// Source: backend/data/georgia_resources.json. Run: npm run sync-corpus.

`;

const header = `export type ResourceCategory =
${typeUnion};

export type Resource = {
  id: string;
  name: string;
  category: ResourceCategory;
  county: string;
  summary: string;
  eligibility: string;
  services: string[];
  contact_phone: string;
  contact_url: string;
  address: string;
  source_name: string;
  last_verified: string;
};

export const CATEGORY_LABEL: Record<ResourceCategory, string> = {
${labelLines}
};

export const CATEGORY_ORDER: ResourceCategory[] = [
${orderLines}
];

export const GEORGIA_RESOURCES: Resource[] = `;

const body = JSON.stringify(cleaned, null, 2) + ";\n";

const footer = `
export const selectResourcesForCounty = (county: string): Resource[] => {
  const c = county.trim();
  if (c === "") {
    return GEORGIA_RESOURCES.filter((r) => r.county === "statewide");
  }
  return GEORGIA_RESOURCES.filter(
    (r) => r.county === "statewide" || r.county.toLowerCase() === c.toLowerCase(),
  );
};

export const groupByCategory = (
  list: Resource[],
): Partial<Record<ResourceCategory, Resource[]>> => {
  const out: Partial<Record<ResourceCategory, Resource[]>> = {};
  for (const r of list) {
    const bucket = out[r.category] ?? [];
    bucket.push(r);
    out[r.category] = bucket;
  }
  return out;
};
`;

writeFileSync(DEST, banner + header + body + footer, "utf8");

console.log(`[sync-corpus] wrote ${cleaned.length} resources → ${DEST}`);
if (cleaned.length !== 52) {
  console.warn(
    `[sync-corpus] WARNING: count is ${cleaned.length}, badge claims 52. ` +
      `Update CORPUS_SIZE in src/lib/corpus.ts or check the backend JSON.`,
  );
}
