// AUTO-GENERATED by frontend/scripts/sync-corpus.mjs. Do not edit by hand.
// Source: backend/data/georgia_resources.json. Run: npm run sync-corpus.

export type ResourceCategory =
  | "education"
  | "housing"
  | "employment"
  | "crisis"
  | "healthcare"
  | "legal"
  | "benefits"
  | "financial"
  | "documents";

export type Resource = {
  id: string;
  name: string;
  category: ResourceCategory;
  county: string;
  summary: string;
  eligibility: string;
  services: string[];
  contact_phone: string;
  contact_url: string;
  address: string;
  source_name: string;
  last_verified: string;
};

export const CATEGORY_LABEL: Record<ResourceCategory, string> = {
  education: "Education",
  housing: "Housing",
  employment: "Work & training",
  crisis: "Crisis",
  healthcare: "Healthcare",
  legal: "Legal",
  benefits: "Benefits portal",
  financial: "Financial",
  documents: "Documents & ID",
};

export const CATEGORY_ORDER: ResourceCategory[] = [
  "crisis",
  "housing",
  "healthcare",
  "education",
  "employment",
  "financial",
  "documents",
  "legal",
  "benefits",
];

export const GEORGIA_RESOURCES: Resource[] = [
  {
    "id": "ascend-ksu-001",
    "name": "KSU ASCEND Program",
    "category": "education",
    "county": "Cobb",
    "summary": "ASCEND supports KSU students with foster care or homelessness experience through campus-based retention help.",
    "eligibility": "KSU students with foster care or homelessness experience.",
    "services": [
      "case management",
      "FAFSA navigation",
      "scholarship access",
      "peer mentoring",
      "on-campus support"
    ],
    "contact_phone": "470-578-5260",
    "contact_url": "https://kennesaw.edu/student-affairs/wellbeing/care-services/ascend-program.php",
    "address": "Kennesaw State University, Kennesaw and Marietta, Georgia",
    "source_name": "KSU ASCEND",
    "last_verified": "2026-04-19"
  },
  {
    "id": "ksu-care-services-001",
    "name": "KSU CARE Services",
    "category": "housing",
    "county": "Cobb",
    "summary": "KSU CARE Services helps students facing housing, food, and emergency basic-needs barriers.",
    "eligibility": "KSU students needing basic-needs or short-term crisis support.",
    "services": [
      "basic needs navigation",
      "temporary housing help",
      "food support",
      "campus referrals"
    ],
    "contact_phone": "470-578-5260",
    "contact_url": "https://kennesaw.edu/student-affairs/wellbeing/care-services/",
    "address": "Kennesaw State University, Kennesaw and Marietta, Georgia",
    "source_name": "KSU CARE Services",
    "last_verified": "2026-04-19"
  },
  {
    "id": "embark-campus-001",
    "name": "Embark Georgia Campus Programs",
    "category": "education",
    "county": "statewide",
    "summary": "Embark Georgia connects students with campus support programs, scholarships, and college persistence help.",
    "eligibility": "Georgia students with foster care or homelessness experience seeking postsecondary support.",
    "services": [
      "campus program matching",
      "scholarship information",
      "college persistence support",
      "student resource navigation"
    ],
    "contact_phone": "",
    "contact_url": "https://embarkgeorgia.org/home",
    "address": "Georgia",
    "source_name": "Embark Georgia",
    "last_verified": "2026-04-19"
  },
  {
    "id": "embark-etv-001",
    "name": "Embark Georgia - Chafee ETV",
    "category": "education",
    "county": "statewide",
    "summary": "Embark Georgia administers Chafee ETV funding for Georgia youth with qualifying foster care history.",
    "eligibility": "Youth ages 18 to 25 with qualifying foster care history and education or training plans.",
    "services": [
      "education voucher funding",
      "application guidance",
      "college and training support"
    ],
    "contact_phone": "",
    "contact_url": "https://embarkgeorgia.org/about-etv/",
    "address": "Georgia",
    "source_name": "Embark Georgia",
    "last_verified": "2026-04-19"
  },
  {
    "id": "connected-by-21-001",
    "name": "Connected By 21",
    "category": "housing",
    "county": "statewide",
    "summary": "Connected By 21 organizes Georgia supports for youth aging out, including housing, life skills, and transition planning.",
    "eligibility": "Georgia youth transitioning from foster care who need post-18 support planning.",
    "services": [
      "transition planning",
      "housing support",
      "life skills coaching",
      "education and employment navigation"
    ],
    "contact_phone": "",
    "contact_url": "https://dhs.georgia.gov/connected-21",
    "address": "Georgia",
    "source_name": "Georgia Department of Human Services",
    "last_verified": "2026-04-19"
  },
  {
    "id": "dfcs-youth-info-001",
    "name": "Georgia DFCS Youth Information",
    "category": "education",
    "county": "statewide",
    "summary": "Georgia DFCS Youth Information highlights transition resources, youth programs, and foster-care planning supports.",
    "eligibility": "Georgia youth in care or transitioning out of care.",
    "services": [
      "youth program information",
      "transition resource links",
      "planning support"
    ],
    "contact_phone": "",
    "contact_url": "https://dfcs.georgia.gov/services/georgia-crew-cultivating-rising-experienced-worker/youth-information",
    "address": "Georgia",
    "source_name": "Georgia DFCS",
    "last_verified": "2026-04-19"
  },
  {
    "id": "ga-crew-001",
    "name": "Georgia CREW",
    "category": "employment",
    "county": "statewide",
    "summary": "Georgia CREW helps youth in care build work readiness, career exposure, and employment skills.",
    "eligibility": "Georgia youth in foster care, generally ages 14 to 21, seeking workforce preparation.",
    "services": [
      "career coaching",
      "job readiness training",
      "mentoring",
      "career exposure"
    ],
    "contact_phone": "",
    "contact_url": "https://dfcs.georgia.gov/services/georgia-crew-cultivating-rising-experienced-worker",
    "address": "Georgia",
    "source_name": "Georgia DFCS",
    "last_verified": "2026-04-19"
  },
  {
    "id": "snap-works-ffy-001",
    "name": "SNAP Works for Former Foster Youth",
    "category": "employment",
    "county": "statewide",
    "summary": "SNAP Works can connect eligible former foster youth to training, credentials, and employment support.",
    "eligibility": "Former foster youth who meet SNAP Works program criteria in participating areas.",
    "services": [
      "job training",
      "industry credentials",
      "employment support",
      "career pathways"
    ],
    "contact_phone": "",
    "contact_url": "https://dfcs.georgia.gov/snap-works-program",
    "address": "Georgia",
    "source_name": "Georgia Department of Human Services",
    "last_verified": "2026-04-19"
  },
  {
    "id": "wellroot-001",
    "name": "Wellroot Family Services",
    "category": "housing",
    "county": "DeKalb",
    "summary": "Wellroot supports youth transitioning from foster care with housing-focused and wraparound services.",
    "eligibility": "Transition-age youth needing housing support, especially youth leaving foster care.",
    "services": [
      "transitional housing",
      "supportive services",
      "youth transition support"
    ],
    "contact_phone": "",
    "contact_url": "https://wellroot.org/",
    "address": "1967 Lakeside Parkway, Suite 400, Tucker, Georgia",
    "source_name": "Wellroot Family Services",
    "last_verified": "2026-04-19"
  },
  {
    "id": "211-ga-001",
    "name": "211 Georgia",
    "category": "crisis",
    "county": "statewide",
    "summary": "211 Georgia connects people to local housing, food, crisis, health, and community services.",
    "eligibility": "Anyone in Georgia needing help finding community resources.",
    "services": [
      "resource navigation",
      "housing referrals",
      "food referrals",
      "crisis referrals"
    ],
    "contact_phone": "211",
    "contact_url": "https://211online.unitedwayatlanta.org/",
    "address": "Georgia",
    "source_name": "211 Georgia",
    "last_verified": "2026-04-19"
  },
  {
    "id": "dfcs-emergency-001",
    "name": "Georgia DFCS Emergency Support",
    "category": "crisis",
    "county": "statewide",
    "summary": "Georgia DFCS provides emergency child welfare and foster-care contact pathways for urgent family or youth safety needs.",
    "eligibility": "Georgia residents needing urgent child welfare or foster-care support.",
    "services": [
      "emergency support",
      "child welfare reporting",
      "county office connection"
    ],
    "contact_phone": "",
    "contact_url": "https://dfcs.georgia.gov/",
    "address": "Georgia",
    "source_name": "Georgia DFCS",
    "last_verified": "2026-04-19"
  },
  {
    "id": "medicaid-extension-001",
    "name": "Georgia Medicaid Extension for Former Foster Youth",
    "category": "healthcare",
    "county": "statewide",
    "summary": "Georgia extends Medicaid for many youth who were in foster care at age 18.",
    "eligibility": "Youth who were in foster care at age 18 may qualify for health coverage through age 26.",
    "services": [
      "health insurance coverage",
      "medical access",
      "coverage information"
    ],
    "contact_phone": "",
    "contact_url": "https://www.childwelfare.gov/resources/extension-foster-care-beyond-age-18-georgia/",
    "address": "Georgia",
    "source_name": "Child Welfare Information Gateway",
    "last_verified": "2026-04-19"
  },
  {
    "id": "eyss-001",
    "name": "Extended Youth Support Services (EYSS)",
    "category": "housing",
    "county": "statewide",
    "summary": "EYSS is part of Georgia's extended foster-care support pathway for eligible youth who aged out at 18.",
    "eligibility": "Youth who aged out at 18 and meet Georgia extended foster-care participation rules.",
    "services": [
      "housing support",
      "life skills support",
      "transition assistance"
    ],
    "contact_phone": "",
    "contact_url": "https://www.childwelfare.gov/resources/extension-foster-care-beyond-age-18-georgia/",
    "address": "Georgia",
    "source_name": "Child Welfare Information Gateway",
    "last_verified": "2026-04-19"
  },
  {
    "id": "cobb-homeless-alliance-001",
    "name": "Cobb Homeless Alliance",
    "category": "housing",
    "county": "Cobb",
    "summary": "Cobb Homeless Alliance coordinates housing providers and homelessness response resources in Cobb County.",
    "eligibility": "Cobb County residents experiencing homelessness or housing instability.",
    "services": [
      "housing coordination",
      "community referrals",
      "continuum of care access"
    ],
    "contact_phone": "770-428-2601",
    "contact_url": "https://cobbhomelessalliance.org/",
    "address": "Cobb County, Georgia",
    "source_name": "Cobb Homeless Alliance",
    "last_verified": "2026-04-19"
  },
  {
    "id": "must-ministries-001",
    "name": "MUST Ministries",
    "category": "housing",
    "county": "Cobb",
    "summary": "MUST Ministries offers emergency assistance, shelter-linked support, food, and basic-needs help in metro Atlanta.",
    "eligibility": "People in crisis needing food, housing support, or basic-needs assistance.",
    "services": [
      "emergency assistance",
      "food support",
      "housing-related help",
      "basic needs support"
    ],
    "contact_phone": "",
    "contact_url": "https://www.mustministries.org/",
    "address": "Marietta, Georgia",
    "source_name": "MUST Ministries",
    "last_verified": "2026-04-19"
  },
  {
    "id": "atlanta-legal-aid-cobb-001",
    "name": "Atlanta Legal Aid - Cobb County",
    "category": "legal",
    "county": "Cobb",
    "summary": "Atlanta Legal Aid's Cobb office helps eligible residents with housing, family, and public-benefits legal issues.",
    "eligibility": "Low-income Cobb County residents with qualifying civil legal needs.",
    "services": [
      "housing law help",
      "public benefits advice",
      "family law support",
      "consumer legal aid"
    ],
    "contact_phone": "",
    "contact_url": "https://www.legalaidprobono.org/cobb/",
    "address": "Cobb County, Georgia",
    "source_name": "Atlanta Legal Aid",
    "last_verified": "2026-04-19"
  },
  {
    "id": "glsp-001",
    "name": "Georgia Legal Services Program",
    "category": "legal",
    "county": "statewide",
    "summary": "Georgia Legal Services Program provides civil legal help to eligible Georgians outside metro Atlanta coverage areas.",
    "eligibility": "Low-income Georgians with qualifying civil legal problems.",
    "services": [
      "civil legal aid",
      "benefits issues",
      "housing law help",
      "family stability support"
    ],
    "contact_phone": "",
    "contact_url": "https://www.glsp.org/",
    "address": "Georgia",
    "source_name": "Georgia Legal Services Program",
    "last_verified": "2026-04-19"
  },
  {
    "id": "georgia-gateway-001",
    "name": "Georgia Gateway",
    "category": "benefits",
    "county": "statewide",
    "summary": "Georgia Gateway is the main online portal for Medicaid, SNAP, TANF, and other state-administered benefits.",
    "eligibility": "Georgia residents applying for public benefits or managing an existing benefits case.",
    "services": [
      "benefit applications",
      "case management",
      "document upload",
      "renewal access"
    ],
    "contact_phone": "877-423-4746",
    "contact_url": "https://gateway.ga.gov/",
    "address": "Georgia",
    "source_name": "Georgia Gateway",
    "last_verified": "2026-04-19"
  },
  {
    "id": "open-bank-guide-001",
    "name": "Opening a Checking or Savings Account in Georgia",
    "category": "financial",
    "county": "statewide",
    "summary": "To open a checking or savings account in Georgia you need a valid photo ID (Georgia state ID, driver's license, or US passport), your Social Security number or ITIN, and proof of current address such as a lease, utility bill, or mail from a government agency. Banks do not run a credit check to open a standard checking or savings account, so a limited or missing credit history does not block you — which is why these accounts are a good fit for foster youth, former foster youth, and other transition-age young adults. Credit unions such as Georgia's Own and Delta Community routinely open accounts for young adults and former foster youth with no credit history. Bank On certified accounts, available at many Georgia banks and credit unions, are designed for people who have been unbanked or underbanked; they have no overdraft fees and a low minimum opening deposit (often $25 or less), which makes them especially useful for youth leaving foster care. If you do not have a current address on file, a DFCS case manager or transitional housing program can help you document a mailing address.",
    "eligibility": "Anyone 18 or older with valid ID and a Social Security number or ITIN. Minors may open joint accounts with a trusted adult.",
    "services": [
      "checking account setup guidance",
      "savings account setup guidance",
      "document checklist for account opening",
      "no-credit-check account options",
      "Bank On certified account referral"
    ],
    "contact_phone": "",
    "contact_url": "https://joinbankon.org/accounts/",
    "address": "Georgia",
    "source_name": "Bank On National Account Standards",
    "last_verified": "2026-04-22"
  },
  {
    "id": "georgias-own-cu-001",
    "name": "Georgia's Own Credit Union",
    "category": "financial",
    "county": "statewide",
    "summary": "Georgia's Own is a member-owned credit union open to anyone who lives, works, worships, or attends school in Georgia. They offer student checking, basic checking, and savings accounts with no monthly fee for eligible accounts and no credit check required to open a standard account. Membership requires a $5 opening deposit into a savings account.",
    "eligibility": "Anyone who lives, works, worships, or attends school in Georgia. $5 minimum opens membership.",
    "services": [
      "checking accounts",
      "savings accounts",
      "debit cards",
      "direct deposit",
      "no-credit-check account opening",
      "financial education"
    ],
    "contact_phone": "404-874-1166",
    "contact_url": "https://www.georgiasown.org/",
    "address": "Georgia",
    "source_name": "Georgia's Own Credit Union",
    "last_verified": "2026-04-22"
  },
  {
    "id": "ssa-card-replacement-001",
    "name": "Replacing a Social Security Card in Georgia",
    "category": "documents",
    "county": "statewide",
    "summary": "To replace a lost or stolen Social Security card, apply through the Social Security Administration (SSA). Replacement cards are free. You need one primary proof of identity — a U.S. driver's license, state-issued ID card, or U.S. passport is preferred. If you don't have any of those, SSA may accept two secondary documents such as an employer ID, school ID, health insurance card (not Medicare), or military ID. You also need to show proof of U.S. citizenship or lawful immigration status if that isn't already on file with SSA; a certified U.S. birth certificate works for citizenship. If you already have a my Social Security online account and a U.S. mailing address, you can usually request the replacement at ssa.gov without visiting an office. Otherwise, apply in person at any Georgia SSA field office. SSA limits replacements to three per year and ten in a lifetime, though replacements tied to a legal name change don't count against those limits. A new card typically arrives in the mail within 10 to 14 business days. If you don't have a photo ID, ask your DFCS case manager — they can often help you get one or write a verification letter the SSA will accept in place of some ID documents.",
    "eligibility": "Anyone with a Social Security number needing a replacement card. U.S. citizens and lawful residents.",
    "services": [
      "Social Security card replacement",
      "lost or stolen card re-issuance",
      "name-change card issuance",
      "online and in-person applications"
    ],
    "contact_phone": "1-800-772-1213",
    "contact_url": "https://www.ssa.gov/ssnumber/ss5doc.htm",
    "address": "Georgia",
    "source_name": "Social Security Administration",
    "last_verified": "2026-04-22"
  },
  {
    "id": "ga-dds-id-foster-youth-001",
    "name": "Getting a Georgia State ID or Driver's License as a Foster Youth",
    "category": "documents",
    "county": "statewide",
    "summary": "The Georgia Department of Driver Services (DDS) issues state ID cards and driver's licenses. Youth currently in foster care and former foster youth who meet DDS eligibility rules can qualify for a fee waiver, meaning the ID or license is issued at no cost. To apply, bring one primary proof of identity (certified U.S. birth certificate, U.S. passport, or permanent resident card), proof of your Social Security number (Social Security card, W-2, or 1099), and two proofs of Georgia residency (lease, utility bill, bank statement, school record, or a letter from a group home or placement provider). Foster youth applying for the fee waiver should also bring documentation of foster-care status — a verification letter from your DFCS case manager is the standard document, and DDS can confirm what they accept at your service center. Apply in person at any Georgia DDS Customer Service Center; most centers issue a temporary paper license the same day and mail the plastic card within 2 to 4 weeks. If you do not yet have a certified birth certificate, get one first — Georgia DPH Vital Records issues them, and a DFCS case manager can help request it on your behalf.",
    "eligibility": "Georgia residents. Fee waiver: youth currently in foster care or former foster youth meeting DDS eligibility criteria. Ask your DFCS case manager for a verification letter.",
    "services": [
      "state ID card issuance",
      "driver's license issuance",
      "foster-youth fee waiver",
      "document requirements for first-time applicants",
      "same-day temporary license"
    ],
    "contact_phone": "678-413-8400",
    "contact_url": "https://dds.georgia.gov/",
    "address": "Georgia",
    "source_name": "Georgia Department of Driver Services",
    "last_verified": "2026-04-22"
  },
  {
    "id": "ga-birth-certificate-001",
    "name": "Getting a Georgia Birth Certificate",
    "category": "documents",
    "county": "statewide",
    "summary": "Georgia birth certificates are issued by the Georgia Department of Public Health (DPH) State Office of Vital Records. A certified copy typically costs $25, with additional copies ordered at the same time at $5 each — fees are set by DPH and can change, so check the Vital Records website for current pricing before you go. You can order the certificate if you are the person named on the record (once you are 18 or older), a parent listed on the record, a spouse, adult child, sibling, grandparent, or a legal guardian with proof of relationship. For youth in foster care, a DFCS case manager has the authority to request a birth certificate on your behalf, and they do this routinely as part of Independent Living Program transition services when youth need vital records for school, benefits, or ID applications — so yes, a caseworker can pull it for you. You can order in person at the State Office of Vital Records in Atlanta or at any Georgia county vital records office (usually fastest, often same-day), by mail using the DPH vital records application form (4 to 6 weeks), or online through the authorized vendor VitalChek (7 to 10 business days, with additional vendor fees). If you were born outside Georgia, Georgia cannot issue another state's birth certificate — you must contact the vital records office of the state where you were born. The CDC's National Center for Health Statistics publishes a directory of every state's vital records office, and a DFCS case manager can help you navigate that. To order, you need a valid photo ID (state ID, driver's license, or U.S. passport). If you do not have a photo ID yet, a DFCS case manager can submit the request on your behalf or help you get an ID first.",
    "eligibility": "Person on the record (age 18+), immediate family with proof of relationship, legal guardian or custodian, or a DFCS case manager acting on behalf of a youth in care.",
    "services": [
      "certified birth certificate issuance",
      "in-person and mail-in orders",
      "VitalChek online orders",
      "out-of-state birth record referrals",
      "DFCS case manager assistance for youth in care",
      "born-out-of-state guidance"
    ],
    "contact_phone": "",
    "contact_url": "https://dph.georgia.gov/vital-records",
    "address": "Georgia",
    "source_name": "Georgia Department of Public Health Vital Records",
    "last_verified": "2026-04-22"
  },
  {
    "id": "ga-tuition-waiver-foster-001",
    "name": "Georgia Tuition and Fee Waiver for Foster Youth",
    "category": "education",
    "county": "statewide",
    "summary": "Georgia state law authorizes a Tuition and Fee Waiver program that waives tuition and mandatory fees at any University System of Georgia (USG) institution — including Kennesaw State, Georgia State, UGA, Georgia Tech, and every other USG college or university — and at any Technical College System of Georgia (TCSG) institution for eligible current and former foster youth. Typical eligibility: you were in Georgia foster care at age 14 or older, you were adopted from Georgia foster care at age 14 or older, or you left foster care through a permanency outcome after age 14. You generally must enroll by age 26, meet the school's regular admission requirements, and maintain Satisfactory Academic Progress. The waiver covers tuition and mandatory fees only — books, housing, food, and transportation are not covered, and most students stack Chafee ETV, Pell Grant, HOPE, Zell Miller, and other aid on top. Coverage typically runs up to a first bachelor's degree or five academic years, whichever comes first. To apply: (1) apply and get admitted to a Georgia public college or university, (2) complete the FAFSA, (3) contact that school's financial aid office to request the tuition waiver, and (4) provide documentation of your foster-care history — a verification letter from a DFCS case manager is the standard document. Embark Georgia campus coordinators at many Georgia public institutions help youth navigate the waiver and stack the rest of the aid package. Exact eligibility rules and documentation can shift year to year — confirm current rules with the Georgia Student Finance Commission (GSFC) and the financial aid office at your school.",
    "eligibility": "Current or former Georgia foster youth, typically with foster-care involvement at age 14 or older. Must enroll by age 26 at a public Georgia college or university. Must meet admission requirements and maintain Satisfactory Academic Progress. Confirm current rules with GSFC and your school's financial aid office.",
    "services": [
      "tuition waiver at public Georgia colleges and universities",
      "mandatory fee waiver",
      "financial aid office application support",
      "DFCS verification letter assistance",
      "coordination with FAFSA, Pell Grant, and Chafee ETV"
    ],
    "contact_phone": "",
    "contact_url": "https://gsfc.georgia.gov/",
    "address": "Georgia",
    "source_name": "Georgia Student Finance Commission",
    "last_verified": "2026-04-22"
  },
  {
    "id": "fafsa-foster-youth-001",
    "name": "FAFSA for Foster Youth in Georgia",
    "category": "education",
    "county": "statewide",
    "summary": "The FAFSA (Free Application for Federal Student Aid) at studentaid.gov is the single form that unlocks federal Pell Grants, subsidized and unsubsidized student loans, work-study, and most Georgia state aid — including the HOPE Scholarship, Zell Miller, and the Georgia Tuition and Fee Waiver for foster youth. Foster youth get a major advantage: you file as an INDEPENDENT STUDENT, which means you do not list any parent information on the form — not your biological parents, not your foster parents, not an adoptive parent, not a guardian. When the FAFSA asks whether at any time since you turned 13 you were in foster care, a dependent or ward of the court, or both your parents were deceased, answer YES. That single answer makes you independent for federal aid purposes, and only your own income (typically low or zero for a transition-age youth) counts in the aid formula — which usually produces a full or near-full Pell Grant. The FAFSA opens each year for the following academic year — in recent years the form has opened in October or December, so check studentaid.gov for the current year's open date. Georgia priority deadlines are school-specific but often fall in winter or early spring, so file as soon as the form opens. To complete the FAFSA you need your Social Security number, a Federal Student Aid ID (FSA ID, created at studentaid.gov), and any tax or income records you have; most foster youth have little or no income to report. If you do not have all your documents yet, your DFCS case manager, an Embark Georgia campus coordinator, KSU ASCEND staff, or the financial aid office at your school can walk you through the form — do not try to do it alone if you hit a question you are unsure about.",
    "eligibility": "Anyone applying for federal or Georgia student aid. Foster youth qualify as independent students and do not list parent information.",
    "services": [
      "federal Pell Grant application",
      "federal student loan eligibility",
      "work-study eligibility",
      "Georgia HOPE and Zell Miller qualification",
      "gateway to Georgia Tuition and Fee Waiver",
      "independent student filing guidance",
      "FSA ID creation"
    ],
    "contact_phone": "1-800-433-3243",
    "contact_url": "https://studentaid.gov/h/apply-for-aid/fafsa",
    "address": "United States",
    "source_name": "U.S. Department of Education Federal Student Aid",
    "last_verified": "2026-04-22"
  },
  {
    "id": "hud-fyi-voucher-001",
    "name": "HUD Foster Youth to Independence (FYI) Voucher",
    "category": "housing",
    "county": "statewide",
    "summary": "The Foster Youth to Independence (FYI) voucher is a federal HUD program that provides rental assistance for youth leaving or aging out of foster care. FYI uses the Housing Choice Voucher framework — the federal government pays a portion of your rent in the private market while you work toward stable income. Eligibility: you must be at least 18 and under 25, you must have left foster care at age 16 or older (or be about to leave at 16+), and you must be homeless or at risk of homelessness. You cannot apply directly to HUD — FYI vouchers are referred to local Public Housing Authorities (PHAs) by the Public Child Welfare Agency, which in Georgia is DFCS. Start the process by telling your DFCS case manager or Independent Living Program specialist that you want an FYI referral; they will contact a participating Georgia PHA on your behalf. Vouchers typically last up to 36 months under current HUD rules and can be paired with self-sufficiency services like employment coaching. Not every Georgia PHA has an active FYI partnership at any given time — availability depends on local HUD, PHA, and DFCS agreements. Georgia PHAs that have historically participated include Atlanta Housing Authority, Marietta Housing Authority (Cobb), DeKalb Housing Authority, and several metro and mid-sized county PHAs. If the PHA in your county is not currently accepting FYI referrals, Connected By 21, Wellroot, and other DFCS-partnered transitional living programs can bridge you to stable housing while you wait.",
    "eligibility": "Age 18 to under 25. Left foster care at age 16 or older (or leaving at 16+). Homeless or at risk of homelessness. Must be referred by DFCS — youth cannot self-apply to HUD.",
    "services": [
      "time-limited rental assistance voucher",
      "referral through DFCS case manager",
      "housing support up to 36 months",
      "fair market rent coverage",
      "self-sufficiency services pairing",
      "PHA coordination"
    ],
    "contact_phone": "",
    "contact_url": "https://www.hud.gov/program_offices/public_indian_housing/programs/hcv/fyi",
    "address": "United States",
    "source_name": "U.S. Department of Housing and Urban Development",
    "last_verified": "2026-04-22"
  },
  {
    "id": "fdic-money-smart-001",
    "name": "FDIC Money Smart for Young People",
    "category": "financial",
    "county": "statewide",
    "summary": "FDIC Money Smart for Young People is a free, plain-language curriculum with modules on earning, spending, saving, borrowing, and protecting money. It does not require an account or sign-up. Topics include how to build a monthly budget, how to track spending against income, how checking and savings accounts work, how to read a bank statement, and how to avoid common financial scams. It is the federal government's standard financial-literacy resource for teens and young adults.",
    "eligibility": "Free and open to anyone. No account required.",
    "services": [
      "budgeting curriculum",
      "spending and saving modules",
      "banking basics",
      "credit and borrowing basics",
      "financial education"
    ],
    "contact_phone": "",
    "contact_url": "https://www.fdic.gov/resources/consumers/money-smart/money-smart-for-young-people/index.html",
    "address": "United States",
    "source_name": "FDIC",
    "last_verified": "2026-04-22"
  }
];

export const selectResourcesForCounty = (county: string): Resource[] => {
  const c = county.trim();
  if (c === "") {
    return GEORGIA_RESOURCES.filter((r) => r.county === "statewide");
  }
  return GEORGIA_RESOURCES.filter(
    (r) => r.county === "statewide" || r.county.toLowerCase() === c.toLowerCase(),
  );
};

export const groupByCategory = (
  list: Resource[],
): Partial<Record<ResourceCategory, Resource[]>> => {
  const out: Partial<Record<ResourceCategory, Resource[]>> = {};
  for (const r of list) {
    const bucket = out[r.category] ?? [];
    bucket.push(r);
    out[r.category] = bucket;
  }
  return out;
};
